/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package z;

import javax.swing.JFrame;

/**
 *
 * @author TIUNIDA12
 */
public class Melihat_harga extends javax.swing.JFrame {

    /**
     * Creates new form lihat
     */
    public Melihat_harga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 510));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("PENGINAPAN JA_RIS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 270, 40);

        jLabel2.setFont(new java.awt.Font("Trajan Pro 3", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("mahasiswa ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 60, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 0));
        jLabel3.setText("Bersahabat Untuk");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 40, 130, 14);

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kamar Sederhana", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 0)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 270, 270, 140);

        jLabel6.setText("Harga       : RP 1.000.000");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 150, 200, 14);

        jLabel7.setText("Fasilitas    : 1. Memiliki 1 Kamar");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 170, 180, 14);

        jLabel8.setText("2. Memiliki 1 toilet");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 350, 210, 14);

        jLabel9.setText("3. Memiliki Halaman Sedang");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 370, 190, 14);

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kamar Mewah", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 0)));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 120, 270, 130);

        jLabel11.setText("Harga     : RP  1.100.000");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 300, 230, 14);

        jLabel12.setText("Fasilitas  : 1. Memiliki 2  Kamar ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 330, 260, 14);

        jLabel13.setText("2. 1 kamar mandi dan 1 toilet");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(400, 190, 250, 14);

        jLabel14.setText("3. Memiliki Teras");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(400, 210, 150, 14);

        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kamar VIP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 0)));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 270, 270, 140);

        jLabel16.setText("Harga       : RP 900.000");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(350, 310, 200, 14);

        jLabel17.setText("Fasilitas    : 1. Memiliki 1 Kamar");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(350, 330, 180, 14);

        jLabel18.setText("2. 1 kamar mandi dan 1 toilet");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(410, 350, 250, 14);

        jLabel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kamar VVIP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 0)));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(10, 130, 280, 120);

        jLabel21.setText("Harga       : RP 1.200.000");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(20, 160, 200, 14);

        jLabel22.setText("Fasilitas    : 1. Memiliki 3 Kamar");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(20, 180, 180, 14);

        jLabel23.setText("2. 1 kamar mandi dan 1 toilet");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(80, 200, 250, 14);

        jLabel24.setText("3. Memiliki Halaman Luas");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(80, 220, 170, 14);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 430, 580, 30);

        jLabel4.setBackground(new java.awt.Color(51, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z/hi.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, -10, 730, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Melihat_harga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Melihat_harga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Melihat_harga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Melihat_harga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Melihat_harga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
