/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package z;

import javax.swing.JFrame;

/**
 *
 * @author TIUNIDA12
 */
public class VVIP extends javax.swing.JFrame {

    /**
     * Creates new form harga_Kamar
     */
    public VVIP() {
        initComponents();
        
        kamar.setEnabled(false);
        kumpul.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kamar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nginap = new javax.swing.JTextField();
        jumlah = new javax.swing.JButton();
        wow = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        kumpul = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(385, 300));
        getContentPane().setLayout(null);

        kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kamarActionPerformed(evt);
            }
        });
        getContentPane().add(kamar);
        kamar.setBounds(148, 54, 198, 30);

        jLabel1.setText("Kamar Pilihan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(18, 64, 63, 14);

        jLabel2.setText("Berapa bulan menginap");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(18, 105, 112, 14);
        getContentPane().add(nginap);
        nginap.setBounds(148, 92, 198, 30);

        jumlah.setText("Jumlah");
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah);
        jumlah.setBounds(18, 133, 328, 30);
        getContentPane().add(wow);
        wow.setBounds(18, 171, 328, 30);

        jButton2.setText("hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(18, 212, 150, 30);

        kumpul.setText("kumpul");
        kumpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kumpulActionPerformed(evt);
            }
        });
        getContentPane().add(kumpul);
        kumpul.setBounds(196, 212, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PEMESANAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 10, 90, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z/Capture.PNG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 970, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        double t,h,b;
        t=Double.parseDouble(String.valueOf(nginap.getText()));
        b=1.2;
        h=t*b;
        wow.setText(h+"00000");
    }//GEN-LAST:event_jumlahActionPerformed

    private void kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kamarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        wow.setText("");
        nginap.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kumpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kumpulActionPerformed
        Biodata_pemesanan.lam.setText(nginap.getText());
        Biodata_pemesanan.ju.setText(wow.getText());
        this.dispose();
    }//GEN-LAST:event_kumpulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVIP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jumlah;
    public static javax.swing.JTextField kamar;
    private javax.swing.JButton kumpul;
    public static javax.swing.JTextField nginap;
    public static javax.swing.JTextField wow;
    // End of variables declaration//GEN-END:variables
}
